"""Add kpis is_inverse column.

Revision ID: 07bc5e3936c0
Revises: 1deb2686d233
Create Date: 2026-09-30 19:32:03.277759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bc5e3936c0'
down_revision: Union[str, Sequence[str], None] = '1deb2686d233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('is_inverse', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpis', 'is_inverse')
    # ### end Alembic commands ###
