"""add kpis description column

Revision ID: 1deb2686d233
Revises: 5138cf77aaf2
Create Date: 2026-09-30 15:51:04.705423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1deb2686d233'
down_revision: Union[str, Sequence[str], None] = '5138cf77aaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpis', 'description')
    # ### end Alembic commands ###
