"""Add organization structure tables: locations, departments, positions, and employees.

Revision ID: 25d95a7ca839
Revises: a1ae4b1dbeb1
Create Date: 2026-09-20 16:29:35.033049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d95a7ca839'
down_revision: Union[str, Sequence[str], None] = 'a1ae4b1dbeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create departments, locations, positions, and employees tables with tenant-isolation RLS.

    Creates the four org-structure tables (each soft-deletable via
    ``deleted_at``), positions' self-referencing ``reports_to_position_id``
    and employees' self-referencing ``manager_id``, plus their supporting
    indexes and check constraints (criticality_type/risk_level on
    positions, employment_type/status on employees). Then enables row
    level security on all four tables and adds a ``tenant_isolation``
    policy on each scoping every row to ``app.current_org_id``.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('revenue_allocation_percentage', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_deleted_at'), 'locations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('positions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('reports_to_position_id', sa.UUID(), nullable=True),
    sa.Column('risk_level', sa.String(length=12), nullable=True),
    sa.Column('criticality_type', sa.String(length=30), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("criticality_type IN ('revenue_generating', 'revenue_enabling', 'operational', 'customer', 'compliance', 'strategic', 'financial', 'legal', 'reputational')", name='check_position_criticality_type'),
    sa.CheckConstraint("risk_level IN ('very_low', 'low', 'medium', 'high', 'very_high')", name='check_position_risk_level'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reports_to_position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_deleted_at'), 'positions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_positions_department_id'), 'positions', ['department_id'], unique=False)
    op.create_index(op.f('ix_positions_organization_id'), 'positions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_positions_reports_to_position_id'), 'positions', ['reports_to_position_id'], unique=False)
    op.create_table('employees',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('work_email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_type IN ('full_time', 'part_time', 'contract', 'temporary', 'intern')", name='check_employee_employment_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='check_employee_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employees_org_location', 'employees', ['organization_id', 'location_id'], unique=False)
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_location_id'), 'employees', ['location_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employees_position_id'), 'employees', ['position_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE departments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE locations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE positions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE employees ENABLE ROW LEVEL SECURITY")

    op.execute(
        """
        CREATE POLICY tenant_isolation ON departments
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY tenant_isolation ON locations
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY tenant_isolation ON positions
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY tenant_isolation ON employees
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Drop the tenant-isolation policies and the employees/positions/locations/departments tables."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON employees")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON positions")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON locations")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON departments")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_position_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_location_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.drop_index('idx_employees_org_location', table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_positions_reports_to_position_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_organization_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_department_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_deleted_at'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_deleted_at'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
