"""Add invite employee link.

Revision ID: 2d57638c6ad3
Revises: 3b698b3af499
Create Date: 2026-10-01 20:47:21.095301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d57638c6ad3'
down_revision: Union[str, Sequence[str], None] = '3b698b3af499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('employee_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_invites_employee_id_employees', 'invites', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invites_employee_id_employees', 'invites', type_='foreignkey')
    op.drop_column('invites', 'employee_id')
    # ### end Alembic commands ###
