"""Add department head.

A nullable link from a department to the one employee HR names as its head
(08_DECISIONS.md 2026-10-06). No data step is needed: every existing
department simply has no head until HR sets one.

Revision ID: 34c5feaf5535
Revises: 774346b5b100
Create Date: 2026-10-06 19:28:14.159972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c5feaf5535'
down_revision: Union[str, Sequence[str], None] = '774346b5b100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add departments.head_employee_id with its index and a named foreign key."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_employee_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_departments_head_employee_id'), 'departments', ['head_employee_id'], unique=False)
    op.create_foreign_key("fk_departments_head_employee_id", 'departments', 'employees', ['head_employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the department head column, its index and its foreign key."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_departments_head_employee_id', 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_head_employee_id'), table_name='departments')
    op.drop_column('departments', 'head_employee_id')
    # ### end Alembic commands ###
