"""Add employee user link uniqueness.

Revision ID: 3b698b3af499
Revises: bfccecca8d49
Create Date: 2026-10-01 18:28:41.381380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b698b3af499'
down_revision: Union[str, Sequence[str], None] = 'bfccecca8d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_employees_org_user_active', 'employees', ['organization_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employees_org_user_active', table_name='employees', postgresql_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'))
    # ### end Alembic commands ###
