"""add refresh tokens, email verification tokens, account status

Revision ID: 3cbcdb2eedc8
Revises: 41f904294609
Create Date: 2026-09-13 17:26:45.304613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbcdb2eedc8'
down_revision: Union[str, Sequence[str], None] = '41f904294609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('users', sa.Column('account_status', sa.String(length=50), server_default='pending_verification', nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###

    # Autogenerate doesn't diff CheckConstraints — added by hand to match the
    # model's __table_args__ (04_DATABASE.md 2026-09-13).
    op.create_check_constraint(
        'check_account_status',
        'users',
        "account_status IN ('pending_verification', 'verified', 'suspended', 'deactivated', 'banned')",
    )

    # memberships.role's server_default was left over from before
    # 08_DECISIONS.md 2026-09-13 removed the column default from the model —
    # autogenerate doesn't diff server defaults either. Dropping it here so a
    # caller that forgets to pass `role` gets a real error instead of
    # silently landing on the DB's leftover default.
    op.alter_column('memberships', 'role', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('memberships', 'role', server_default='employee')
    op.drop_constraint('check_account_status', 'users', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('users', 'account_status')
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
