"""Add kpis tracking_mode column.

Revision ID: 5138cf77aaf2
Revises: ba28e47d3238
Create Date: 2026-09-30 05:24:38.769859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5138cf77aaf2'
down_revision: Union[str, Sequence[str], None] = 'ba28e47d3238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add kpis.tracking_mode, defaulted to 'manual', with a value CHECK.

    See 08_DECISIONS.md 2026-09-30: decides whether a KPI's mid-quarter
    progress is a live task count ('task_count', needs M10's tasks table)
    or a typed-in figure ('manual', the only mode usable before then).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('tracking_mode', sa.String(length=20), server_default='manual', nullable=False))
    # ### end Alembic commands ###

    op.create_check_constraint(
        'check_kpi_tracking_mode',
        'kpis',
        "tracking_mode IN ('manual', 'task_count')",
    )


def downgrade() -> None:
    """Drop the tracking_mode CHECK constraint and column."""
    op.drop_constraint('check_kpi_tracking_mode', 'kpis', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpis', 'tracking_mode')
    # ### end Alembic commands ###
