"""add password reset tokens, extend memberships RLS for login

Revision ID: 5a2e8e70ce1e
Revises: 3cbcdb2eedc8
Create Date: 2026-09-15 03:13:25.516525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2e8e70ce1e'
down_revision: Union[str, Sequence[str], None] = '3cbcdb2eedc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Extend memberships' tenant-isolation policy for login (08_DECISIONS.md
    # 2026-09-15). Login has to look up which org(s) a user belongs to
    # *before* any org has been chosen — the same "no badge yet" bootstrap
    # problem as organizations'/memberships' own creation, but on the read
    # side this time, which the original policy never carved an exception
    # for. The fix is scoped narrowly: a session with no org context yet may
    # see ONLY its own rows (matched by app.current_user_id, set by the login
    # flow right after password verification), never every organization's
    # memberships. WITH CHECK (the write side) is unchanged — writes still
    # only get the org-creation bootstrap exception, never a user-scoped one.
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON memberships")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON memberships
        USING (
            organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
            OR (
                NULLIF(current_setting('app.current_org_id', true), '') IS NULL
                AND user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
            )
        )
        WITH CHECK (
            NULLIF(current_setting('app.current_org_id', true), '') IS NULL
            OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON memberships")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON memberships
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (
            NULLIF(current_setting('app.current_org_id', true), '') IS NULL
            OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
        )
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
