"""Add department name uniqueness.

Revision ID: 61454952170a
Revises: ee15b3a6eb57
Create Date: 2026-09-24 14:33:00.066754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61454952170a'
down_revision: Union[str, Sequence[str], None] = 'ee15b3a6eb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make department names unique per organization (normalized, non-deleted only).

    Adds ``name_normalized`` (a database-generated comparison key: NFKC,
    trimmed, whitespace collapsed, lowercased) and a partial unique index on
    (``organization_id``, ``name_normalized``) ``WHERE deleted_at IS NULL`` —
    per organization so two companies can both have an "Operations", and
    non-deleted only so a deleted department's name can be reused.

    Existing data may already contain duplicates (nothing enforced this
    before), and the unique index would refuse to build over them. So
    before creating it, any duplicate among non-deleted departments is
    renamed with a numeric suffix — the oldest keeps its name unchanged,
    newer ones become "Name (2)", "Name (3)" — preserving every row and
    only changing display names. Runs under the migration role, which
    bypasses RLS, so it sees every organization. Not reversed on
    downgrade: the renames are left in place.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('name_normalized', sa.Text(), sa.Computed("lower(regexp_replace(btrim(normalize(name, NFKC)), '\\s+', ' ', 'g'))", persisted=True), nullable=False))

    op.execute(
        """
        WITH ranked AS (
            SELECT id,
                   row_number() OVER (
                       PARTITION BY organization_id, name_normalized
                       ORDER BY created_at, id
                   ) AS rn
            FROM departments
            WHERE deleted_at IS NULL
        )
        UPDATE departments d
        SET name = d.name || ' (' || ranked.rn || ')'
        FROM ranked
        WHERE d.id = ranked.id AND ranked.rn > 1
        """
    )

    op.create_index('uq_departments_org_name_active', 'departments', ['organization_id', 'name_normalized'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the uniqueness index and the generated column (dedupe renames are kept)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_departments_org_name_active', table_name='departments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('departments', 'name_normalized')
    # ### end Alembic commands ###
