"""Add attendance records.

Revision ID: 83927f74b4eb
Revises: 8bff259ac5fb
Create Date: 2026-10-02 11:23:27.618318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83927f74b4eb'
down_revision: Union[str, Sequence[str], None] = '8bff259ac5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create attendance_records with its indexes, constraints and RLS policy."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('clock_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=20), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("closed_by IN ('employee', 'system')", name='check_attendance_closed_by'),
    sa.CheckConstraint('(clock_out_at IS NULL AND closed_by IS NULL AND close_reason IS NULL) OR (clock_out_at IS NOT NULL AND closed_by IS NOT NULL)', name='check_attendance_closed_fields_together'),
    sa.CheckConstraint('clock_out_at IS NULL OR clock_out_at >= clock_in_at', name='check_attendance_out_after_in'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendance_employee_clock_in', 'attendance_records', ['organization_id', 'employee_id', 'clock_in_at'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_organization_id'), 'attendance_records', ['organization_id'], unique=False)
    op.create_index('uq_attendance_one_open_per_employee', 'attendance_records', ['employee_id'], unique=True, postgresql_where=sa.text('clock_out_at IS NULL'))
    # ### end Alembic commands ###

    op.execute("ALTER TABLE attendance_records ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON attendance_records
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Drop the tenant-isolation policy and the attendance_records table."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON attendance_records")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_one_open_per_employee', table_name='attendance_records', postgresql_where=sa.text('clock_out_at IS NULL'))
    op.drop_index(op.f('ix_attendance_records_organization_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index('idx_attendance_employee_clock_in', table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
