"""Add organization timezone.

Revision ID: 8bff259ac5fb
Revises: 1f55b227d9d9
Create Date: 2026-10-02 09:44:59.408803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bff259ac5fb'
down_revision: Union[str, Sequence[str], None] = '1f55b227d9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('timezone', sa.String(length=64), server_default='Africa/Lagos', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'timezone')
    # ### end Alembic commands ###
