"""add kpis and kpi_scores tables

Revision ID: ba28e47d3238
Revises: c56f442c2848
Create Date: 2026-09-29 17:39:10.051972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba28e47d3238'
down_revision: Union[str, Sequence[str], None] = 'c56f442c2848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create kpis and kpi_scores tables with tenant-isolation RLS.

    Creates ``kpis`` (department- or location-scoped KPIs, optionally
    tracing to a Key Result) and ``kpi_scores`` (one row per KPI per
    scoring period, deliberately no ``deleted_at`` — a closed period's
    score is permanent history), then enables row level security on both
    and adds a ``tenant_isolation`` policy on each scoping every row to
    ``app.current_org_id``.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('key_result_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('target_value', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 100', name='check_kpi_weight_range'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['key_result_id'], ['key_results.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_deleted_at'), 'kpis', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_kpis_department_id'), 'kpis', ['department_id'], unique=False)
    op.create_index(op.f('ix_kpis_key_result_id'), 'kpis', ['key_result_id'], unique=False)
    op.create_index(op.f('ix_kpis_location_id'), 'kpis', ['location_id'], unique=False)
    op.create_index(op.f('ix_kpis_organization_id'), 'kpis', ['organization_id'], unique=False)
    op.create_table('kpi_scores',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('actual_value', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('score_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_scores_kpi_id'), 'kpi_scores', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_kpi_scores_organization_id'), 'kpi_scores', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE kpis ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE kpi_scores ENABLE ROW LEVEL SECURITY")

    op.execute(
        """
        CREATE POLICY tenant_isolation ON kpis
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY tenant_isolation ON kpi_scores
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Drop the tenant-isolation policies and the kpi_scores/kpis tables."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON kpi_scores")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON kpis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_scores_organization_id'), table_name='kpi_scores')
    op.drop_index(op.f('ix_kpi_scores_kpi_id'), table_name='kpi_scores')
    op.drop_table('kpi_scores')
    op.drop_index(op.f('ix_kpis_organization_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_location_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_key_result_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_department_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_deleted_at'), table_name='kpis')
    op.drop_table('kpis')
    # ### end Alembic commands ###
