"""Add kpi_weight suggestion type columns.

Revision ID: bfccecca8d49
Revises: 07bc5e3936c0
Create Date: 2026-09-30 22:09:54.533881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfccecca8d49'
down_revision: Union[str, Sequence[str], None] = '07bc5e3936c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add kpi_weight's target columns, widen both CHECKs, and the pending-duplicate index.

    Autogenerate catches the new columns/index/FK but not CHECK
    constraints on an existing table (it only sees those on CREATE TABLE),
    so both are dropped and recreated by hand here to add the
    ``kpi_weight`` branch/value.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_suggestions', sa.Column('kpi_id', sa.UUID(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('suggested_weight', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('ai_suggestions', sa.Column('reviewed_weight', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.drop_index('idx_ai_suggestions_unique_pending', table_name='ai_suggestions', postgresql_where="((status)::text = 'pending'::text)", postgresql_nulls_not_distinct=True)
    op.create_index('idx_ai_suggestions_unique_pending', 'ai_suggestions', ['organization_id', 'suggestion_type', 'position_id', 'department_id', 'suggested_department_name_normalized', 'kpi_id'], unique=True, postgresql_where=sa.text("status = 'pending'"), postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_ai_suggestions_kpi_id'), 'ai_suggestions', ['kpi_id'], unique=False)
    op.create_foreign_key(None, 'ai_suggestions', 'kpis', ['kpi_id'], ['id'])
    # ### end Alembic commands ###

    op.drop_constraint('check_ai_suggestion_type', 'ai_suggestions', type_='check')
    op.create_check_constraint(
        'check_ai_suggestion_type',
        'ai_suggestions',
        "suggestion_type IN ('critical_position', 'revenue_allocation', "
        "'missing_department', 'kpi_weight')",
    )

    op.drop_constraint('check_ai_suggestion_target_matches_type', 'ai_suggestions', type_='check')
    op.create_check_constraint(
        'check_ai_suggestion_target_matches_type',
        'ai_suggestions',
        "(suggestion_type = 'critical_position' AND position_id IS NOT NULL "
        "AND suggested_criticality_type IS NOT NULL AND suggested_risk_level IS NOT NULL) OR "
        "(suggestion_type = 'revenue_allocation' AND department_id IS NOT NULL "
        "AND suggested_revenue_allocation_percentage IS NOT NULL) OR "
        "(suggestion_type = 'missing_department' AND suggested_department_name IS NOT NULL) OR "
        "(suggestion_type = 'kpi_weight' AND kpi_id IS NOT NULL "
        "AND suggested_weight IS NOT NULL)",
    )


def downgrade() -> None:
    """Revert both CHECKs and drop kpi_weight's target columns."""
    op.drop_constraint('check_ai_suggestion_target_matches_type', 'ai_suggestions', type_='check')
    op.create_check_constraint(
        'check_ai_suggestion_target_matches_type',
        'ai_suggestions',
        "(suggestion_type = 'critical_position' AND position_id IS NOT NULL "
        "AND suggested_criticality_type IS NOT NULL AND suggested_risk_level IS NOT NULL) OR "
        "(suggestion_type = 'revenue_allocation' AND department_id IS NOT NULL "
        "AND suggested_revenue_allocation_percentage IS NOT NULL) OR "
        "(suggestion_type = 'missing_department' AND suggested_department_name IS NOT NULL)",
    )
    op.drop_constraint('check_ai_suggestion_type', 'ai_suggestions', type_='check')
    op.create_check_constraint(
        'check_ai_suggestion_type',
        'ai_suggestions',
        "suggestion_type IN ('critical_position', 'revenue_allocation', 'missing_department')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_suggestions', type_='foreignkey')
    op.drop_index(op.f('ix_ai_suggestions_kpi_id'), table_name='ai_suggestions')
    op.drop_index('idx_ai_suggestions_unique_pending', table_name='ai_suggestions', postgresql_where=sa.text("status = 'pending'"), postgresql_nulls_not_distinct=True)
    op.create_index('idx_ai_suggestions_unique_pending', 'ai_suggestions', ['organization_id', 'suggestion_type', 'position_id', 'department_id', 'suggested_department_name_normalized'], unique=True, postgresql_where="((status)::text = 'pending'::text)", postgresql_nulls_not_distinct=True)
    op.drop_column('ai_suggestions', 'reviewed_weight')
    op.drop_column('ai_suggestions', 'suggested_weight')
    op.drop_column('ai_suggestions', 'kpi_id')
    # ### end Alembic commands ###
