"""add membership deactivated_at, scope deactivation per-org

Revision ID: ce685af9fd0d
Revises: c5e6d0ff6fec
Create Date: 2026-09-18 11:42:54.250490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce685af9fd0d'
down_revision: Union[str, Sequence[str], None] = 'c5e6d0ff6fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'deactivated_at')
    # ### end Alembic commands ###
