"""add business dna tables

Revision ID: d4016005348b
Revises: 25d95a7ca839
Create Date: 2026-09-21 06:23:42.095165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4016005348b'
down_revision: Union[str, Sequence[str], None] = '25d95a7ca839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_dna',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('products_services_description', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('performance_philosophy', sa.Text(), nullable=True),
    sa.Column('workforce_rules', sa.Text(), nullable=True),
    sa.Column('revenue_drivers', sa.Text(), nullable=True),
    sa.Column('operational_drivers', sa.Text(), nullable=True),
    sa.Column('customer_value_drivers', sa.Text(), nullable=True),
    sa.Column('capital_investment_amount', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('business_dna_core_values',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('business_dna_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_dna_id'], ['business_dna.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_dna_core_values_business_dna_id'), 'business_dna_core_values', ['business_dna_id'], unique=False)
    op.create_index(op.f('ix_business_dna_core_values_organization_id'), 'business_dna_core_values', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE business_dna ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE business_dna_core_values ENABLE ROW LEVEL SECURITY")

    op.execute(
        """
        CREATE POLICY tenant_isolation ON business_dna
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY tenant_isolation ON business_dna_core_values
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON business_dna_core_values")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON business_dna")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_dna_core_values_organization_id'), table_name='business_dna_core_values')
    op.drop_index(op.f('ix_business_dna_core_values_business_dna_id'), table_name='business_dna_core_values')
    op.drop_table('business_dna_core_values')
    op.drop_table('business_dna')
    # ### end Alembic commands ###
