"""Add ai_suggestions and ai_usage_log tables.

Revision ID: ee15b3a6eb57
Revises: 80d102d22686
Create Date: 2026-09-23 20:58:42.336913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee15b3a6eb57'
down_revision: Union[str, Sequence[str], None] = '80d102d22686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create ai_usage_log and ai_suggestions tables with tenant-isolation RLS.

    Creates ``ai_usage_log`` (one row per LLM call, for cost/usage
    tracking) and ``ai_suggestions`` (AI-proposed changes awaiting human
    review), then enables row level security on both and adds a
    ``tenant_isolation`` policy on each scoping every row to
    ``app.current_org_id``. RLS is the only thing hand-added here — the
    tables, the generated column, and every index (including the partial
    unique one) are declared on the models and rendered by autogenerate.

    ``idx_ai_suggestions_unique_pending`` enforces "one pending suggestion
    per target" and makes retried Celery generation jobs safe via
    ``INSERT ... ON CONFLICT DO NOTHING``. Two things about it are
    load-bearing, both verified against the dev DB during M7 (08_DECISIONS.md
    2026-09-23): ``NULLS NOT DISTINCT`` (every suggestion type leaves two of
    its three target columns null, and a standard unique index never treats
    two nulls as equal, so without it the index never fires), and keying on
    ``suggested_department_name_normalized`` — a database-generated
    comparison key — instead of the raw LLM-written name, so case/spacing/
    Unicode variants of the same name count as the same target.

    The rejected-suggestion quarterly-suppression rule (08_DECISIONS.md
    2026-09-22) is deliberately not enforced here: it compares
    ``reviewed_at`` against a quarter boundary computed at query time,
    which can't be an immutable index predicate, so it lives in
    application code. Only three of the eventual four ``suggestion_type``
    values exist yet — ``kpi_weight`` arrives with M8's migration once
    ``kpis`` exists.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('ai_suggestion_generation', 'executive_summary_generation')", name='check_ai_usage_log_purpose'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_log_organization_id'), 'ai_usage_log', ['organization_id'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=30), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('suggested_department_name', sa.Text(), nullable=True),
    sa.Column('suggested_department_name_normalized', sa.Text(), sa.Computed("lower(regexp_replace(btrim(normalize(suggested_department_name, NFKC)), '\\s+', ' ', 'g'))", persisted=True), nullable=True),
    sa.Column('suggested_criticality_type', sa.Text(), nullable=True),
    sa.Column('suggested_risk_level', sa.Text(), nullable=True),
    sa.Column('suggested_revenue_allocation_percentage', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_criticality_type', sa.Text(), nullable=True),
    sa.Column('reviewed_risk_level', sa.Text(), nullable=True),
    sa.Column('reviewed_revenue_allocation_percentage', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('reviewed_department_name', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(suggestion_type = 'critical_position' AND position_id IS NOT NULL AND suggested_criticality_type IS NOT NULL AND suggested_risk_level IS NOT NULL) OR (suggestion_type = 'revenue_allocation' AND department_id IS NOT NULL AND suggested_revenue_allocation_percentage IS NOT NULL) OR (suggestion_type = 'missing_department' AND suggested_department_name IS NOT NULL)", name='check_ai_suggestion_target_matches_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'edited', 'rejected')", name='check_ai_suggestion_status'),
    sa.CheckConstraint("suggestion_type IN ('critical_position', 'revenue_allocation', 'missing_department')", name='check_ai_suggestion_type'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_suggestions_unique_pending', 'ai_suggestions', ['organization_id', 'suggestion_type', 'position_id', 'department_id', 'suggested_department_name_normalized'], unique=True, postgresql_where=sa.text("status = 'pending'"), postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_ai_suggestions_department_id'), 'ai_suggestions', ['department_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_organization_id'), 'ai_suggestions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_position_id'), 'ai_suggestions', ['position_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_reviewed_at'), 'ai_suggestions', ['reviewed_at'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE ai_usage_log ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ai_suggestions ENABLE ROW LEVEL SECURITY")

    op.execute(
        """
        CREATE POLICY tenant_isolation ON ai_usage_log
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY tenant_isolation ON ai_suggestions
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Drop the tenant-isolation policies, then the ai_suggestions/ai_usage_log tables."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON ai_suggestions")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON ai_usage_log")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_suggestions_reviewed_at'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_position_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_organization_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_department_id'), table_name='ai_suggestions')
    op.drop_index('idx_ai_suggestions_unique_pending', table_name='ai_suggestions', postgresql_where=sa.text("status = 'pending'"), postgresql_nulls_not_distinct=True)
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_ai_usage_log_organization_id'), table_name='ai_usage_log')
    op.drop_table('ai_usage_log')
    # ### end Alembic commands ###
