"""Database engine, session factory, and abstract base models."""

import uuid
from datetime import datetime

from sqlalchemy import UUID, DateTime, func
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, mapped_column, Mapped

from app.core.config import settings

engine = create_async_engine(
    settings.database_url,
    echo=settings.debug,  # logs SQL in debug mode only
    pool_pre_ping=True,  # drops stale connections before use
    pool_size=10,
    max_overflow=20,
)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False
)


class Base(DeclarativeBase):
    """SQLAlchemy declarative base for all ORM models."""


class BaseModel(Base):
    """Abstract base model with shared audit fields.

    Provides common columns that every concrete model inherits automatically:

    Attributes:
        id: UUID primary key generated by Python (not the database),
            ensuring uniqueness before the row is persisted.
        created_at: Timezone-aware timestamp set by the database on INSERT.
        updated_at: Timezone-aware timestamp refreshed by the database on
            every UPDATE.

    Note:
        This class is abstract (``__abstract__ = True``) and does not
        produce its own database table.

    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


    

